#!/usr/bin/python

import json
import sys


properties = {}


if len(sys.argv) == 1:
	print >> stderr, 'SYNTAX: {0} name=value ...'.format(sys.argv[0])
	sys.exit(1)

for arg in sys.argv[1:]:
	if '=' in arg:
		name,value = arg.split('=')
	else:
		name,value = [arg,'*']
	
	properties[name] = value


for line in sys.stdin:
	line = line.strip()
	
	if line != '' and line[0] != '#':
		d = json.loads(line)
		
		for name,value in properties.iteritems():
			if name in d:
				if value == '*' or d[name] == value:
					print line
